package com.sn.onepay.controller;

import com.sn.onepay.dto.AuditLogDTO;
import com.sn.onepay.enumeration.AuditSeverity;
import com.sn.onepay.services.AuditLogService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import lombok.AccessLevel;
import lombok.RequiredArgsConstructor;
import lombok.experimental.FieldDefaults;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDateTime;

/*Read-only: audit entries are system-generated by AuditLoggingInterceptor, never created/updated through the API*/
@Slf4j
@FieldDefaults(level = AccessLevel.PRIVATE)
@RestController
@RequestMapping(value = "/v1/onepay/auditLog")
@RequiredArgsConstructor
public class AuditLogController {

    final AuditLogService auditLogService;

    @Operation(summary = "Get audit log entries by filters", description = "This endpoint is for getting audit log entries by filters")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "400", description = "Incorrect request"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @GetMapping
    @ResponseStatus(HttpStatus.OK)
    public Page<AuditLogDTO> getAuditLogsByFilters(@Parameter(description = "Filter by audit log entry ID") @RequestParam(required = false) Long id,
                                                    @Parameter(description = "Filter by event type (partial match)") @RequestParam(required = false) String eventType,
                                                    @Parameter(description = "Filter by actor username (partial match)") @RequestParam(required = false) String actorUsername,
                                                    @Parameter(description = "Filter by severity") @RequestParam(required = false) AuditSeverity severity,
                                                    @Parameter(description = "Filter by IP address (partial match)") @RequestParam(required = false) String ipAddress,
                                                    @Parameter(description = "Filter by active status (true or false)") @RequestParam(required = false) Boolean active,
                                                    @Parameter(description = "Filter records created after this date (ISO format)") @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime creationDate,
                                                    @Parameter(description = "Filter records modified before this date (ISO format)") @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime modificationDate,
                                                    Pageable pageable) {
        return auditLogService.getAuditLogsByFilters(id, eventType, actorUsername, severity, ipAddress, active, creationDate, modificationDate, pageable);
    }

    @Operation(summary = "Get an audit log entry by id", description = "This endpoint returns a single audit log entry by its id")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Success"),
            @ApiResponse(responseCode = "404", description = "Not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @GetMapping("/{auditLogId}")
    @ResponseStatus(HttpStatus.OK)
    public AuditLogDTO getAuditLogById(@Parameter(description = "Audit log entry id", required = true) @PathVariable(name = "auditLogId") Long auditLogId) {
        return auditLogService.getAuditLogById(auditLogId);
    }
}
