spring:
  application:
    name: OnePay-Backend
  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/onepay}
    username: ${SPRING_DATASOURCE_USERNAME:onepay}
    password: ${SPRING_DATASOURCE_PASSWORD:onepay}

  liquibase:
    change-log: classpath:db.changelog-master.xml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: postgresql

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

server:
  port: 8086